name: chat_messanger_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.1.7
  custom_pop_up_menu: ^1.2.0

  cupertino_icons: ^0.1.3
  line_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - images/like.gif
    - images/love.gif
    - images/haha.gif
    - images/wow.gif
    - images/sad.gif
    - images/angry.gif
    - images/angry2.png
    - images/love2.png
    - images/haha2.png
    - images/wow2.png
    - images/sad2.png
    - images/ic_like.png
    - images/ic_like_fill.png

    - sounds/box_down.mp3
    - sounds/box_up.mp3
    - sounds/icon_choose.mp3
    - sounds/icon_focus.mp3
    - sounds/short_press_like.mp3
